{
    "name": "fkame",
    "version": "0",

    "ghc-options": "-Wall -Wincomplete-record-updates -Wincomplete-uni-patterns",

    "default-extensions": [
        "ApplicativeDo",
        "ConstraintKinds",
        "DataKinds",
        "DeriveAnyClass",
        "DeriveGeneric",
        "DerivingStrategies",
        "FlexibleContexts",
        "GeneralizedNewtypeDeriving",
        "OverloadedLists",
        "OverloadedStrings",
        "ScopedTypeVariables",
        "StrictData",
        "TypeOperators"
    ],

    "dependencies": [
        "aeson",
        "base",
        "containers",
        "http-api-data",
        "lens",
        "mtl",
        "network-uri",
        "servant",
        "servant-server",
        "text",
        "vector",
        "warp"
    ],

    "library": {
        "source-dirs": [
            "library"
        ]
    },

    "executables": {
        "example": {
            "source-dirs": [
                "executables/example"
            ],
            "main": "Main.hs",
            "dependencies": [
                "fkame"
            ]
        }
    },

    "tests": {
        "unit-test": {
            "source-dirs": [
                "unit-tests"
            ],
            "main": "Main.hs",
            "dependencies": [
                "fkame",
                "hspec"
            ]
        }
    }
}
